version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  # frontend ディレクトリを /app にマウント
      - /app/node_modules  # node_modules をボリュームとして持つことでコンテナ内部と切り離す
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
